
services:
  db:
    container_name: db
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER} # for the psql client
      PGPASSWORD: ${POSTGRES_PASSWORD} # for the psql client
      PGDATABASE: ${POSTGRES_DB} # for the psql client
    ports:
      - "5433:5432" # expose container 5432 as host 5433
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgtmp:/tmp


  # pgadmin:
  #   container_name: pgadmin
  #   image: elestio/pgadmin:REL-8_10
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "5050:80" # type localhost:5050 to your browser to access the UI

